services:
  pg:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: maindb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d maindb"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 10s

  enrollment:
    build: .
    environment:
      ENROLLMENT_PORT: 8080
      ENROLLMENT_PG_HOST: pg
      ENROLLMENT_PG_USER: admin
      ENROLLMENT_PG_PASSWORD: admin
      ENROLLMENT_PG_DATABASE: maindb
      TZ: Europe/Moscow
    ports:
      - 80:8080
    depends_on:
      pg:
        condition: service_healthy