"""empty message

Revision ID: 5461e7f3ee61
Revises: 
Create Date: 2022-09-15 21:46:46.374284

"""
from alembic import op
import sqlalchemy as sa
from enrollment.db.types import __custom_types__ as types


# revision identifiers, used by Alembic.
revision = '5461e7f3ee61'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('file', 'folder', name='type'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('parentId', sa.String(), nullable=False),
    sa.Column('childId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['childId'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentId'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parentId', 'childId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('items')
    # ### end Alembic commands ###
    for type in types:
        type.drop(op.get_bind(), checkfirst=False)
